@url = http://localhost:4400

GET {{url}}/posts 

###
POST {{url}}/posts
Content-Type: application/json

{
    "newpost": "Testing from TEST API"
}

###

DELETE {{url}}/posts/24

###
POST {{url}}/upload
Content-Type: multipart/form-data; boundary=imageboundary

--imageboundary
Content-Disposition: form-data; name="image"; filename="image1.jpg"
Content-Type: image/png

< ./image1.png
--imageboundary--